### ISSUE TITLE
Make test directory, show problem with ccov_api

### ISSUE THREAD

**Issue by klahnakoski** [chinhodado/codecoverage_presenter#1]
A test directory, containing HTML pages, that verify features can help with debugging modules.  Specifically, I could not find the entry point for ccov_api.js that revealed the problem Greg mentioned.

Please make a page that builds a JsonCcov object and attempts to make the problematic call.  I can then debug the problem.

**Comment by gmierz** [comment]
I'm very sorry for the trouble! I'll have a test file ready for you in a little bit. It's going to be very simple without much of an interface. Is that ok?

**Comment by gmierz** [comment]
I've made a simple HTML test page that shows the problem in the "tests/" directory. It's logged in the console. I don't know if this problem will still be relevant or not after I make some of your suggested modifications. I am thinking that if I can change to an AJAX call with a callback method on success then the problem should be solved.

**Comment by klahnakoski** [comment]
Sorry for the delay.   The problem is `QueryFilesOfTest.prototype.performQuery` is launching a "thread"[1] and returning immediately, before the result is populated.  

To fix this, you can choose to use `thread.js` throughout, or include callbacks in all your functions.  As an example of the former, your test would make a call like this:

```
Thread.run(function*(){  //ENTER WORLD OF GENERATOR CODE
    var ccov = new JsonCcov();
    var query = new QueryFilesOfTest("chrome://mochitests/content/browser/addon-sdk/test/browser_sdk_loader_chrome.js");
    ccov.setQuery(query);
    var results = yield (ccov.getQueryResults());  //YIELD WAITS FOR RESULT
    console.log("This line is after the query is performed. Next line in the console log should not be undefined but it is. ")
    console.log(results);
});
```

Of course, I left out that fact that all your functions that (eventually) make a network request must be generators (`function*(){}`).

If you use callbacks, your test code would look like this:

```
ccov.setQuery(query);
var results = ccov.getQueryResults(function(results){
    console.log("This line is after the query is performed. Next line in the console log should not be undefined but it is. ")
    console.log(results);
 });
```

Again, all your functions that can be paused due to network requests must have a callback for when the request is complete.

[1] all threads in quotes because there is no actual parallel execution

**Comment by klahnakoski** [comment]
Added pull request with a full answer

https://github.com/chinhodado/codecoverage_presenter/pull/7

**Comment by klahnakoski** [comment]
I suggest you download them and use your favorite diff viewer to see what changes I made.

**Comment by gmierz** [comment]
Thanks for the excellent comments/suggestions Kyle! I'll make the necessary modifications to the API in the next few days, before our next meeting.
