### ISSUE TITLE
figure out why unique source files sometimes is only the test file - ignore those if possible

### ISSUE THREAD

**Issue by jmaher** [chinhodado/codecoverage_presenter#11]
here is a case where we only seem to have a unique source file of itself:
http://chinhodado.github.io/codecoverage_presenter/?buildRevision=232db2940e992fe4c998dbb0a498703fbf463e0d&query=2&select2=chrome%3A%2F%2Fmochitests%2Fcontent%2Fbrowser%2Faddon-sdk%2Ftest%2Fbrowser_sdk_loader_js_modules.js

in the test selection field if there is only lines covered from the test case itself (or I would argue any test related file), then we shouldn't show it.

The trick here is that we would need to run the query for all test files- this is the case to argue for adding more meta data into active data (post ingestion task)

**Comment by jmaher** [comment]
this is confusing when you look at the query "given a source file which tests cover it" and the source file is the test file- lets fix this

**Comment by chinhodado** [comment]
Fixed. See #9.

**Comment by jmaher** [comment]
yeah, this is nice!
