### ISSUE TITLE
static urls do not load accurately

### ISSUE THREAD

**Issue by jmaher** [chinhodado/codecoverage_presenter#13]
load this:
http://chinhodado.github.io/codecoverage_presenter/?buildRevision=232db2940e992fe4c998dbb0a498703fbf463e0d&query=3&select2=resource%3A%2F%2Fgre%2Fmodules%2FUITelemetry.jsm

and you will see the last drop down on the page to be empty- this makes it hard to know what source/test file you are querying on.

**Comment by chinhodado** [comment]
This is a known problem. The issue is some dropdowns have dependency on other dropdowns and populate them in a way that is consistent with both using static url and not is a bit difficult. I'm working on converting the selects into textboxes which will probably make this problem go away.

**Comment by chinhodado** [comment]
Fixed
