### ISSUE TITLE
Use $.ajax ?

### ISSUE THREAD

**Issue by klahnakoski** [chinhodado/codecoverage_presenter#3]
ActiveData is agnostic about the client libraries you use.  Your code can completely liberate itself from the `modevlib` library by using `$.ajax()` (which uses callbacks), like so...

```
    var search = function(query, callback){
        $.ajax({
            url: "https://activedata.allizom.org/query",
            data: JSON.stringify(query),
            success: callback
        });
    };
```

**Comment by chinhodado** [comment]
Currently I'm using `Thread.js` which seems to do the job well. I will keep the other options (callback, promise, etc.) in mind.
