### ISSUE TITLE
Given all known tests, what's the coverage % of a given file

### ISSUE THREAD

**Issue by klahnakoski** [chinhodado/codecoverage_presenter#5]
I believe the canonical code coverage UI is to show the percentage of lines covered by testing.  If it can be done for one, then it can be done for all files, all directories.

Let user select a file. Then, show all the code lines of that file, and highlight the lines covered.

**Comment by chinhodado** [comment]
This requires the following:
- See the coverage % of a given file <- done, will be available when https://github.com/klahnakoski/TestLog-ETL/commits/codecoverage_new_format is merged and data is in ActiveData
- Show all the code lines of that file, and highlight the lines covered <- this can be done using dxr ([example](https://dxr.mozilla.org/mozilla-central/source/testing/mozbase/mozlog/setup.py#12,14,16)). However it requires being able to map a source file name correctly to dxr, which is not possible yet.

**Comment by chinhodado** [comment]
Regarding the second point, a lot of time a search on dxr for a file name will only return one result ([example](https://dxr.mozilla.org/mozilla-central/search?q=path%3Abrowser_987177_xul_wrapper_updating.js&redirect=false&case=false)). In this case, it is probably possible to do a "heuristic" matching.

**Comment by chinhodado** [comment]
This is implemented:

http://chinhodado.github.io/codecoverage_presenter/index.html?buildRevision=232db2940e992fe4c998dbb0a498703fbf463e0d&query=5&select2=chrome%3A%2F%2Fbrowser%2Fcontent%2Fbrowser-customization.js
