### ISSUE TITLE
test files names should be reduced

### ISSUE THREAD

**Issue by jmaher** [chinhodado/codecoverage_presenter#8]
for example:
chrome://mochitests/content/browser/toolkit/mozapps/extensions/test/xpinstall/browser_whitelist2.js

should be:
toolkit/mozapps/extensions/test/xpinstall/browser_whitelist2.js

**Comment by chinhodado** [comment]
I'm not sure what the best way to handle this is. In particular I'm not sure if putting the logic of trimming file path on the front end is the best idea. Maybe that should be done directly in the produced jscov file? Or when doing the transform to insert the data into ActiveData?

**Comment by jmaher** [comment]
I would prefer to see if this works in the front end, and if there are no issues we can determine where to fix it (generation, db insertion)

**Comment by chinhodado** [comment]
I implemented this (https://github.com/chinhodado/codecoverage_presenter/commit/b886725d7438840f998c4c7e631733fd68e699ca). But what about when the test files are not from `chrome://mochitests/content/browser/`?

**Comment by jmaher** [comment]
lets leave the filename alone, we can find a few patterns and implement it as needed.

**Comment by chinhodado** [comment]
Do you mean that only the file name (e.g. `browser_whitelist2.js`) should be displayed?

**Comment by jmaher** [comment]
no, I see that we have toolkit/.../browser_whitelist2.js

this way we have a relative path in the source tree.

**Comment by chinhodado** [comment]
I believe this is now implemented as you described, @jmaher?

**Comment by jmaher** [comment]
yes, lets close this!
