### ISSUE TITLE
hide or fade out test related files from all queries

### ISSUE THREAD

**Issue by jmaher** [chinhodado/codecoverage_presenter#9]
in a query we show a nice list of files, but the test related files are not that useful for most people.

We can hide or show at the bottom (or even strikethrough/color) these type of files:
resource://testing-common
chrome://mochikit
chrome://mochitests
chrome://specialpowers

ideally each file that is displayed in the UI as part of a query would have a tag associated with it- all of the above ones should have a 'test file' tag and we can make the UI match what we want.

**Comment by chinhodado** [comment]
Files that contains the above prefix are now considered test files and are no longer shown in
- list of source files to be selected as input for a query
- list of source files touched by a test, as a result of a query.

Implemented in https://github.com/chinhodado/codecoverage_presenter/commit/e782d25f5585eb0abc004bb768e187375e889f51
